name: Trigger site rebuild

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps: [
      { name: 'Checkout', uses: actions/checkout@v4, with: { fetch-depth: 1 } },
      { name: 'Install Python', uses: actions/setup-python@v4, with: { python-version: 3.10.5, architecture: x64 } },
      {
        name: 'Create archives',
        run: 'python create_archives.py'
      },
      {
        name: "Create tag",
        run: 'git tag v${{ github.sha }}'
      },
      {
        name: "Push to tag",
        run: 'git push origin v${{ github.sha }}'
      },
      {
        name: 'Release',
        uses: softprops/action-gh-release@v2,
        with: { files: "*.zip", make_latest: true, tag_name: 'v${{ github.sha }}' }
      },
      {
        name: 'Repository dispatch',
        uses: defold/repository-dispatch@1.2.1,
        with: {
            repo: 'defold/defold.github.io',
            token: '${{ secrets.SERVICES_GITHUB_TOKEN }}',
            user: 'services@defold.se',
            action: 'examples'
        }
      }
    ]
