function init(self)
	local bounds = model.get_aabb("/train#model")
	local aabb = vmath.vector4(bounds.min.x, bounds.min.y, bounds.max.x, bounds.max.y)
	go.set("/train#model", "model_aabb", aabb)
end

function final(self)
end

function update(self, dt)
end

function fixed_update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
end
